apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: pedrohenriquesc/backend
          ports:
            - containerPort: 8181
          env:
            - name: DATABASE_URL
              value: postgresql://admin:admin123@postgres:5432/meubanco
