apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: backend
  newName: pedrohenriquesc/backend
  newTag: c58b625834eb8b45c0d3d3b45ba4cbc288fc5146
- name: packer-vagrant-virtualbox-main
  newName: pedrohenriquesc/backend
  newTag: d232839806477d0626c78d848a6698b947e136bf
