apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: backend
  newName: pedrohenriquesc/backend
  newTag: c58b625834eb8b45c0d3d3b45ba4cbc288fc5146
- name: backend  
  newName: pedrohenriquesc/backend
<<<<<<< Updated upstream
  newTag: 89e360a0054a3f858d4df578e78ebce710e347c3
=======
  newTag: novatagdb
>>>>>>> Stashed changes
