name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            pedrohenriquesc/backend:latest
            pedrohenriquesc/backend:${{ github.sha }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update kustomization.yaml
        run: |
          cd k8s
          kustomize edit set image packer-vagrant-virtualbox-main=pedrohenriquesc/backend:$GITHUB_SHA

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN_PUSH }}@github.com/pedrohenriquemoreiram/Backend-devops.git
          git add k8s/kustomization.yaml
          git commit -m "Update kustomization.yaml with new image" || echo "No changes to commit"
          git push origin main
          
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN_PUSH }}@github.com/pedrohenriquemoreiram/Backend-devops.git
          git add k8s/kustomization.yaml
          git commit -m "Update kustomization.yaml with new image" || echo "No changes to commit"
          git push origin main

      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN_PUSH }}
          branch: ${{ github.ref }}
